baseURL = "http://example.com"
title = "JCW Maker"
author = "C.J. Wade"
theme = "simple-snipcart-shop"
contentDir = "products"
[params]
  instagram = "jcw_maker"
  header = "Welcome to My Portfolio!"
  description = "Custom Leatherwork"
  products_title = "My Products"
  reviews_title = "Our reviews"
  not_found = "Sorry, but we do not have any products in this category yet."
  categories = [
    "For you",
    "For the home",
    "For the friends"
  ]
  collage = [
    "/images/leather-01.jpg",
    "/images/leather-02.jpg",
    "/images/leather-03.jpg",
    "/images/leather-04.jpg",
    "/images/leather-05.jpg",
    "/images/leather-06.jpg",
    "/images/leather-07.jpg",
    "/images/leather-08.jpg"
  ]
  # snipcart features will not work without an api key
  # see https://docs.snipcart.com/v3/dashboard/account-configuration#3-api-keys
  # snipcart_key = ""
  favicon= "/images/favicon.png"
  logo= "/images/logo.png"

