baseURL = "http://example.com"
title = "JCW Maker"
author = "C.J. Wade"
theme = "simple-snipcart-shop"
contentDir = "products"
[params]
  instagram = "jcw_maker"
  facebook = "jcw_maker"
  header = "Welcome to My Portfolio!"
  description = "Custom Leatherwork"
  products_title = "My Products"
  #reviews_title = "Our reviews"
  not_found = "Sorry, but we do not have any products in this category yet."
  categories = [
    "Wallets",
    "Belt Slides",
    "Money Clips"
  ]
  collage = [
    "/images/belt-slide-brown-cross-hatch-basket-01.jpg",
    "/images/bifold-money-clip-oil-finish-basket-weave-double-border-01.jpg",
    "/images/drury-wallet-brown-cross-hatch-basket-01.jpg",
    "/images/dr/ury-wallet-two-tone-basket-weave-01.jpg",
    "/images/leamon-money-clip-basket-weave-double-border-01.jpg",
    "/images/leamon-money-clip-tooled-texas-01.jpg",
    "/images/roper-wallet-two-tone-01.jpg",
    "/images/belt-slide-two-tone-cross-hatch-01.jpg"
  ]
  # snipcart features will not work without an api key
  # see https://docs.snipcart.com/v3/dashboard/account-configuration#3-api-keys
  # snipcart_key = ""
  favicon= "/images/favicon.png"